# Generated by Django 4.2.6 on 2023-11-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_advertisement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
