# Generated by Django 4.2.6 on 2023-10-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='content',
        ),
    ]
