# Generated by Django 4.2.6 on 2023-10-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_remove_flexpage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexpage',
            old_name='subtitle',
            new_name='banner_subtitle',
        ),
    ]
