# Generated by Django 4.2.6 on 2023-11-04 04:30

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_rename_subtitle_flexpage_banner_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='body',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
