# Generated by Django 4.2.6 on 2023-11-14 15:49

from django.db import migrations
import django.utils.timezone
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_flexpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='superNova',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], default=django.utils.timezone.now, use_json_field=True),
            preserve_default=False,
        ),
    ]
