# Generated by Django 4.2.6 on 2023-11-22 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
    ]
