# Generated by Django 4.2.6 on 2023-12-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_navbar_navitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navitem',
            name='navbar',
        ),
        migrations.RemoveField(
            model_name='navitem',
            name='page',
        ),
        migrations.DeleteModel(
            name='Navbar',
        ),
        migrations.DeleteModel(
            name='NavItem',
        ),
    ]
