# Generated by Django 4.2.6 on 2023-12-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_remove_navbar_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='page',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
